apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgadmin
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: pgadmin-email
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: pgadmin-password
          image: dpage/pgadmin4:latest
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:80/misc/ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: pgadmin
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /pgadmin4/servers.json
              name: pgadmin-claim0
      restartPolicy: Always
      volumes:
        - name: pgadmin-claim0
          persistentVolumeClaim:
            claimName: pgadmin-claim0
