apiVersion: v1
data:
  definitions.json: |
    {
      "rabbit_version": "3.13.0",
      "rabbitmq_version": "3.13.0",
      "users": [
        {
          "name": "guest",
          "password_hash": "hGVJTDI0rZrQO2GcfedJ7N3bFUiGMLP1mubmkrWy2jMcYVLm",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": ["administrator"]
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "queues": [
        {
          "name": "ocr-worker-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "genai-worker-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "ocr-result-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        },
        {
          "name": "genai-result-queue",
          "vhost": "/",
          "durable": true,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [],
      "bindings": []
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq-cm2
