apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: webui
  name: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webui
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: webui
    spec:
      containers:
        - env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: /api
          image: webui
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - wget
                - --no-verbose
                - --tries=1
                - --spider
                - http://localhost:3000
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          name: webui
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always

