apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workers
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kubernetes\Kompose\kompose.exe convert -f ../docker-compose.yml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: workers
    spec:
      containers:
        - env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: minio-root-user
            - name: MINIO_BUCKET_NAME
              value: documents
            - name: MINIO_ENDPOINT
              value: minio
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: minio-root-password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: openai-api-key
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbitmq-password
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbitmq-user
          image: workers
          imagePullPolicy: Never
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - java
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          name: workers
      restartPolicy: Always

